# omnivoice_generate.py
"""Helper module to generate audio using the OmniVoice model.

Provides a single function ``generate_omnivoice(instruct: str, output_name: str)``
that loads the OmniVoice model (cached globally) and writes the generated
WAV file to the system temporary directory.
"""

import os
import tempfile
import soundfile as sf
from omnivoice import OmniVoice

# Load the model once at import time. Adjust device_map as needed.
_model = OmniVoice.from_pretrained(
    "k2-fsa/OmniVoice",
    device_map="cpu",  # change to "cuda:0" if a GPU is available
    dtype="float16",
)

def generate_omnivoice(instruct: str, output_name: str, text: str = "") -> str:
    """Generate audio with OmniVoice.

    Args:
        instruct: The instruction string that describes the voice characteristics.
                 If empty string, generate without instruction.
        output_name: Desired filename (without path). The function will save the
            file to the system temporary directory and return the full path.
        text: Optional custom text to generate. Defaults to placeholder.

    Returns:
        The absolute path to the generated WAV file.
    """
    # Use provided text or default placeholder
    if not text:
        text = "Hello, this is a test generated by OmniVoice."
    
    # Generate with or without instruct based on whether it's provided
    if instruct:
        audio = _model.generate(text=text, instruct=instruct)
    else:
        audio = _model.generate(text=text)
    
    # audio is a list of numpy arrays; take the first element.
    wav_path = os.path.join(tempfile.gettempdir(), output_name)
    sf.write(wav_path, audio[0], 24000)
    return wav_path
